package net.warp.android.data

/**
 * Node configuration data class
 * Contains all necessary information to connect to a WarpNet desktop node
 */
data class NodeConfig(
    val peerId: String, // Generated by libp2p node
    val sessionToken: String, // Token received by scanning QR code
    val psk: ByteArray? = null,
    val bootstrapNodes: List<String> = WARPNET_BOOTSTRAP_NODES
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as NodeConfig

        if (peerId != other.peerId) return false
        if (sessionToken != other.sessionToken) return false
        if (psk != null) {
            if (other.psk == null) return false
            if (!psk.contentEquals(other.psk)) return false
        } else if (other.psk != null) return false
        if (bootstrapNodes != other.bootstrapNodes) return false

        return true
    }

    override fun hashCode(): Int {
        var result = peerId.hashCode()
        result = 31 * result + sessionToken.hashCode()
        result = 31 * result + (psk?.contentHashCode() ?: 0)
        result = 31 * result + bootstrapNodes.hashCode()
        return result
    }
    
    companion object {
        // WarpNet mainnet bootstrap nodes
        val WARPNET_BOOTSTRAP_NODES = listOf(
            "/ip4/207.154.221.44/tcp/4001/p2p/12D3KooWMKZFrp1BDKg9amtkv5zWnLhuUXN32nhqMvbtMdV2hz7j",
            "/ip4/207.154.221.44/tcp/4002/p2p/12D3KooWSjbYrsVoXzJcEtmgJLMVCbPXMzJmNN1JkEZB9LJ2rnmU",
            "/ip4/207.154.221.44/tcp/4003/p2p/12D3KooWNXSGyfTuYc3JznW48jay73BtQgHszWfPpyF581EWcpGJ"
        )
        
        // WarpNet testnet bootstrap nodes
        val TESTNET_BOOTSTRAP_NODES = listOf(
            "/ip4/207.154.221.44/tcp/4011/p2p/12D3KooWMKZFrp1BDKg9amtkv5zWnLhuUXN32nhqMvbtMdV2hz7j",
            "/ip4/207.154.221.44/tcp/4022/p2p/12D3KooWSjbYrsVoXzJcEtmgJLMVCbPXMzJmNN1JkEZB9LJ2rnmU",
            "/ip4/207.154.221.44/tcp/4033/p2p/12D3KooWNXSGyfTuYc3JznW48jay73BtQgHszWfPpyF581EWcpGJ"
        )
    }
}

/**
 * Connection status enum
 */
enum class ConnectionStatus {
    DISCONNECTED,
    CONNECTING,
    CONNECTED,
    ERROR
}

/**
 * QR code data parsed from desktop node
 */
data class QRCodeData(
    val peerId: String,
    val addresses: List<String>,
    val sessionToken: String,
    val psk: String? = null
)
